<?php

return [
    'default_preference' => 'light',
    'fallback_theme' => 'light',
    'preferences' => ['light', 'dark', 'system'],
    'resolved' => ['light', 'dark'],

    'themes' => [
        'light' => [
            'label' => 'Light',
            'tokens' => [
                'surface' => '#F8F9FF',
                'surface-secondary' => '#EFF4FF',
                'elevated' => '#FFFFFF',
                'card' => '#FFFFFF',
                'sidebar' => '#FFFFFF',
                'header' => '#FFFFFF',
                'muted' => '#E5EEFF',
                'border-default' => '#C3C6D7',
                'border-subtle' => 'rgba(11, 28, 48, 0.08)',
                'text-primary' => '#0B1C30',
                'text-secondary' => '#434655',
                'text-muted' => '#737686',
                'overlay' => 'rgba(11, 28, 48, 0.45)',
                'shadow' => '0 8px 24px rgba(11, 28, 48, 0.08)',
                'blur' => '12px',
                'input-bg' => '#FFFFFF',
                'table-stripe' => '#F8F9FF',
                'table-hover' => '#EFF4FF',
                'code-bg' => '#EFF4FF',
                'gradient-soft' => 'linear-gradient(135deg, #F8F9FF 0%, #EFF4FF 100%)',
                'icon-bg' => '#DBE1FF',
                'icon-fg' => '#004AC6',
                'primary' => '#004AC6',
                'primary-hover' => '#2563EB',
                // Interactive companion blue (links/hovers); success green is `success`
                'accent' => '#2563EB',
                'success' => '#006243',
                'danger' => '#BA1A1A',
                'warning' => '#F59E0B',
            ],
            'rgb' => [
                'surface' => '248 249 255',
                'elevated' => '255 255 255',
                'muted' => '229 238 255',
                'card' => '255 255 255',
                'primary' => '0 74 198',
                'primary-hover' => '37 99 235',
                'accent' => '37 99 235',
                'success' => '0 98 67',
                'danger' => '186 26 26',
            ],
            'charts' => [
                'background' => '#FFFFFF',
                'grid' => '#C3C6D7',
                'labels' => '#737686',
                'legend' => '#434655',
                'tooltipBg' => '#0B1C30',
                'tooltipText' => '#F8F9FF',
                'axis' => '#737686',
                'crosshair' => '#004AC6',
                'selection' => 'rgba(0, 74, 198, 0.15)',
                'hover' => 'rgba(0, 74, 198, 0.25)',
            ],
            'assets' => [
                'logo' => 'assets/images/originla_logo.png',
                'logo_fallback' => 'assets/images/originla_logo.png',
                'empty.default' => null,
                'empty.wallet' => null,
                'empty.marketplace' => null,
                'empty.dashboard' => null,
            ],
        ],
        'dark' => [
            'label' => 'Dark',
            'tokens' => [
                'surface' => '#0B1220',
                'surface-secondary' => '#111827',
                'elevated' => '#152238',
                'card' => 'rgba(21, 34, 56, 0.72)',
                'sidebar' => '#152238',
                'header' => 'rgba(21, 34, 56, 0.85)',
                'muted' => '#2A3548',
                'border-default' => '#2A3548',
                'border-subtle' => 'rgba(255, 255, 255, 0.1)',
                'text-primary' => '#E8EEF9',
                'text-secondary' => '#A8B0C0',
                'text-muted' => '#8B93A7',
                'overlay' => 'rgba(2, 6, 23, 0.65)',
                'shadow' => '0 8px 32px rgba(0, 0, 0, 0.35)',
                'blur' => '12px',
                'input-bg' => 'rgba(21, 34, 56, 0.55)',
                'table-stripe' => 'rgba(42, 53, 72, 0.35)',
                'table-hover' => 'rgba(42, 53, 72, 0.55)',
                'code-bg' => '#111827',
                'gradient-soft' => 'linear-gradient(135deg, #0B1220 0%, #0A1A3A 100%)',
                'icon-bg' => 'rgba(180, 197, 255, 0.18)',
                'icon-fg' => '#B4C5FF',
                'primary' => '#2563EB',
                'primary-hover' => '#3B82F6',
                'accent' => '#B4C5FF',
                'success' => '#68DBA9',
                'danger' => '#BA1A1A',
                'warning' => '#F59E0B',
            ],
            'rgb' => [
                'surface' => '11 18 32',
                'elevated' => '21 34 56',
                'muted' => '42 53 72',
                'card' => '21 34 56',
                'primary' => '37 99 235',
                'primary-hover' => '59 130 246',
                'accent' => '180 197 255',
                'success' => '104 219 169',
                'danger' => '186 26 26',
            ],
            'charts' => [
                'background' => '#0B1220',
                'grid' => '#2A3548',
                'labels' => '#A8B0C0',
                'legend' => '#E8EEF9',
                'tooltipBg' => '#152238',
                'tooltipText' => '#F8F9FF',
                'axis' => '#8B93A7',
                'crosshair' => '#2563EB',
                'selection' => 'rgba(37, 99, 235, 0.2)',
                'hover' => 'rgba(37, 99, 235, 0.3)',
            ],
            'assets' => [
                'logo' => 'assets/images/white_originla_logo.png',
                'logo_fallback' => 'assets/images/originla_logo.png',
                'empty.default' => null,
                'empty.wallet' => null,
                'empty.marketplace' => null,
                'empty.dashboard' => null,
            ],
        ],
    ],
];
