<?php

return [
    'user' => [
        [
            'type' => 'link',
            'id' => 'dashboard',
            'label' => 'Dashboard',
            'route' => 'dashboard',
            'match' => ['dashboard'],
            'icon' => 'home',
            'keywords' => ['home', 'overview'],
            'sort' => 10,
        ],
        [
            'type' => 'link',
            'id' => 'services',
            'label' => 'Services',
            'route' => 'dashboard.services',
            'match' => ['dashboard.services', 'dashboard.services.*', 'dashboard.discover.services', 'dashboard.discover.services.*'],
            'icon' => 'listings',
            'keywords' => ['catalog', 'platform', 'buy', 'services', 'browse', 'social'],
            'sort' => 20,
        ],
        [
            'type' => 'link',
            'id' => 'my-tools',
            'label' => 'My Tools',
            'route' => 'dashboard.my-tools',
            'match' => ['dashboard.my-tools', 'dashboard.my-tools.*'],
            'icon' => 'listings',
            'keywords' => ['tools', 'owned', 'services', 'social'],
            'sort' => 25,
        ],
        [
            'type' => 'link',
            'id' => 'service-orders',
            'label' => 'My Orders',
            'route' => 'dashboard.service-orders',
            'match' => ['dashboard.service-orders', 'dashboard.service-orders.*'],
            'icon' => 'orders',
            'keywords' => ['purchases', 'platform', 'service orders'],
            'sort' => 28,
        ],
        [
            'type' => 'link',
            'id' => 'wallet',
            'label' => 'My Wallet',
            'route' => 'dashboard.wallet',
            'match' => ['dashboard.wallet', 'dashboard.wallet.*', 'dashboard.deposit.*', 'dashboard.withdrawal.*', 'dashboard.history'],
            'icon' => 'wallet',
            'keywords' => ['balance', 'funds', 'deposit', 'withdraw', 'history'],
            'sort' => 55,
        ],
        [
            'type' => 'link',
            'id' => 'support',
            'label' => 'Support',
            'route' => 'dashboard.support.index',
            'match' => ['dashboard.support.*'],
            'icon' => 'support',
            'keywords' => ['tickets', 'help', 'contact'],
            'sort' => 60,
        ],
        [
            'type' => 'link',
            'id' => 'settings',
            'label' => 'Settings',
            'route' => 'dashboard.account.profile',
            'match' => ['dashboard.account.*'],
            'icon' => 'settings',
            'keywords' => ['profile', 'account', 'security', 'kyc', 'preferences'],
            'sort' => 70,
        ],
    ],
    'admin' => [
        [
            'type' => 'link',
            'id' => 'overview',
            'label' => 'Overview',
            'route' => 'admin',
            'match' => ['admin'],
            'icon' => 'home',
            'keywords' => ['home', 'dashboard'],
            'sort' => 5,
        ],
        [
            'type' => 'group',
            'id' => 'operations',
            'label' => 'Operations',
            'icon' => 'users',
            'sort' => 10,
            'children' => [
                ['route' => 'admin.users', 'match' => ['admin.users', 'admin.users.*'], 'label' => 'Users', 'icon' => 'users', 'keywords' => ['members', 'accounts'], 'permission' => 'users.manage', 'sort' => 10],
                ['route' => 'admin.administrators', 'match' => ['admin.administrators', 'admin.administrators.*'], 'label' => 'Administrators', 'icon' => 'verified', 'keywords' => ['admins', 'staff'], 'permission' => 'admins.manage', 'sort' => 20],
                ['route' => 'admin.kyc', 'match' => ['admin.kyc', 'admin.kyc.*'], 'label' => 'KYC', 'icon' => 'kyc', 'keywords' => ['identity', 'verification'], 'permission' => 'compliance.manage', 'sort' => 30],
                ['route' => 'admin.tickets', 'match' => ['admin.tickets', 'admin.tickets.*'], 'label' => 'Support', 'icon' => 'support', 'keywords' => ['help', 'tickets'], 'permission' => 'support.manage', 'sort' => 40],
                ['route' => 'admin.fees-limits', 'match' => ['admin.fees-limits', 'admin.fees-limits.*'], 'label' => 'Fees & Limits', 'icon' => 'paid', 'keywords' => ['fees', 'limits', 'deposit', 'withdrawal'], 'permission' => 'fees.manage', 'sort' => 45],
                ['route' => 'admin.audit-logs', 'match' => ['admin.audit-logs', 'admin.audit-logs.*'], 'label' => 'Audit Logs', 'icon' => 'audit', 'keywords' => ['logs', 'activity'], 'permission' => 'system.manage', 'sort' => 50],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'platform-catalog',
            'label' => 'Platform Catalog',
            'icon' => 'storefront',
            'sort' => 20,
            'children' => [
                ['route' => 'admin.service-categories', 'match' => ['admin.service-categories', 'admin.service-categories.*'], 'label' => 'Service Categories', 'icon' => 'grid', 'keywords' => ['catalog', 'categories'], 'permission' => 'catalog.manage', 'sort' => 10],
                ['route' => 'admin.services', 'match' => ['admin.services', 'admin.services.*'], 'label' => 'Services', 'icon' => 'listings', 'keywords' => ['catalog', 'services', 'types'], 'permission' => 'catalog.manage', 'sort' => 20],
                ['route' => 'admin.platform-products', 'match' => ['admin.platform-products', 'admin.platform-products.*'], 'label' => 'Products', 'icon' => 'storefront', 'keywords' => ['prod', 'catalog', 'products'], 'permission' => 'catalog.manage', 'sort' => 30],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'finance',
            'label' => 'Finance',
            'icon' => 'wallet',
            'sort' => 50,
            'children' => [
                ['route' => 'admin.fundings', 'match' => ['admin.fundings', 'admin.fundings.*'], 'label' => 'Deposits', 'icon' => 'deposit', 'keywords' => ['fundings', 'bank'], 'permission' => 'finance.manage', 'sort' => 10],
                ['route' => 'admin.orders', 'match' => ['admin.orders', 'admin.orders.*'], 'label' => 'Orders', 'icon' => 'orders', 'keywords' => ['platform', 'manual bank', 'services'], 'permission' => 'finance.manage', 'sort' => 12],
                ['route' => 'admin.withdrawals', 'match' => ['admin.withdrawals', 'admin.withdrawals.*'], 'label' => 'Withdrawals', 'icon' => 'withdraw', 'keywords' => ['payouts'], 'permission' => 'finance.manage', 'sort' => 20],
                ['route' => 'admin.reconciliation', 'match' => ['admin.reconciliation', 'admin.reconciliation.*'], 'label' => 'Reconciliation', 'icon' => 'audit', 'keywords' => ['monnify', 'webhooks', 'fix'], 'permission' => 'finance.manage', 'sort' => 25],
                ['route' => 'admin.wallet-adjustment', 'match' => ['admin.wallet-adjustment', 'admin.wallet-adjustment.*'], 'label' => 'Wallet Adjustments', 'icon' => 'wallet-adjust', 'keywords' => ['credit', 'debit', 'adjust'], 'permission' => 'finance.manage', 'sort' => 30],
                ['route' => 'admin.transactions', 'match' => ['admin.transactions', 'admin.transactions.*'], 'label' => 'Transactions', 'icon' => 'transactions', 'keywords' => ['ledger', 'history'], 'permission' => 'finance.manage', 'sort' => 40],
            ],
        ],
        [
            'type' => 'group',
            'id' => 'system',
            'label' => 'System',
            'icon' => 'settings',
            'sort' => 60,
            'children' => [
                ['route' => 'admin.settings', 'match' => ['admin.settings', 'admin.settings.branding', 'admin.settings.contact', 'admin.settings.social', 'admin.settings.google-identity', 'admin.settings.google-identity.test'], 'label' => 'Site Settings', 'icon' => 'settings', 'keywords' => ['platform', 'config', 'branding', 'contact'], 'permission' => 'system.manage', 'sort' => 5],
                ['route' => 'admin.settings.email-settings', 'match' => ['admin.settings.email-settings', 'admin.settings.email', 'admin.settings.test-mail'], 'label' => 'Email Settings', 'icon' => 'messages', 'keywords' => ['brevo', 'smtp', 'mail'], 'permission' => 'system.manage', 'sort' => 6],
                ['route' => 'admin.settings.payments', 'match' => ['admin.settings.payments', 'admin.settings.monnify', 'admin.settings.monnify.test', 'admin.settings.manual-bank-transfer'], 'label' => 'Payment Settings', 'icon' => 'wallet', 'keywords' => ['monnify', 'bank transfer', 'gateway'], 'permission' => 'system.manage', 'sort' => 7],
                ['route' => 'admin.analytics', 'match' => ['admin.analytics', 'admin.analytics.*'], 'label' => 'Analytics', 'icon' => 'analytics', 'keywords' => ['reports', 'metrics'], 'permission' => 'analytics.view', 'sort' => 10],
                ['route' => 'admin.monitoring', 'match' => ['admin.monitoring', 'admin.monitoring.*'], 'label' => 'Monitoring', 'icon' => 'audit', 'keywords' => ['health', 'heartbeat', 'system'], 'permission' => 'system.manage', 'sort' => 12],
                ['route' => 'admin.media', 'match' => ['admin.media', 'admin.media.*'], 'label' => 'Media Library', 'icon' => 'listings', 'keywords' => ['media', 'images', 'upload'], 'permission' => 'system.manage', 'sort' => 15],
                ['route' => 'admin.tracking', 'match' => ['admin.tracking', 'admin.tracking.*'], 'label' => 'Marketing & Tracking', 'icon' => 'analytics', 'keywords' => ['gtm', 'pixel', 'scripts', 'clarity', 'ga'], 'permission' => 'system.manage', 'sort' => 23],
            ],
        ],
    ],
];
